name: Build Example

"on":
  push:
    branches: [master, main]

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
      - name: 📄 Compile Examples
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            example.tex
            visualizer-doc.tex
      - name: Install PU for previews
        run: sudo apt install poppler-utils
      - name: 🖼️ Generate preview
        run: |
          pdftoppm -png -r 400 ./build/example.pdf example
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "./build/example.pdf" "example-1.png" "./build/visualizer-doc.pdf"
          git commit -m "Newly compiled data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true