name: Build Example

"on":
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
      - name: ⏱️ Benchmark
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_lualatex: false
          work_in_root_file_dir: false
          root_file: bench/bench.tex
          pre_compile: sh bench/run.sh
          post_compile: "true"
      - name: 📄 Compile Examples
        uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "diffutils" # l3build needs GNU diff, not busybox
          pre_compile: l3build check
          root_file: |
            example.tex
            visualizer-doc.tex
      - name: Install PU for previews
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - name: 🖼️ Generate preview
        run: |
          pdftoppm -png -r 400 ./build/example.pdf example
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "./build/example.pdf" "example-1.png" "./build/visualizer-doc.pdf" "./build/bench.pdf" "bench/bench-results.tex"
          git commit -m "Newly compiled data" || echo "nothing new to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true